image: node:lts

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - .next/cache/
    - .pnpm-store/ # Cache pnpm store for faster installs

before_script:
  - corepack enable
  - pnpm install

build_job:
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - out/
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - mv public out
    - mv out public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  dependencies:
    - build_job
  artifacts:
    paths:
      - public
  only:
    - main