backend:
  name: gitlab
  repo: AWD-2069/WPCJC
  branch: main
  auth_type: pkce
  app_id: 10bfa9d8d0fe5cbaca2b79693542aee0498a162912784c79d442b110ca7365d2

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "sections"
    label: "Sections"
    folder: "content/sections"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "order", widget: "number", required: false }
      - { label: "Description", name: "description", widget: "text", required: false }

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - label: "Section"
        name: "section"
        widget: "relation"
        collection: "sections"
        search_fields: ["title"]
        value_field: "title"
        required: false
      - label: "Hero Section"
        name: "hero"
        widget: "object"
        fields:
          - { label: "Heading", name: "heading", widget: "string", required: false }
          - { label: "Description", name: "hero_description", widget: "text", required: false }
          - { label: "Join Us Text", name: "join_us", widget: "string", required: false }
          - { label: "Background Image", name: "backgroundImage", widget: "image", required: false }
      - label: "Components"
        name: "components"
        widget: "list"
        required: false
        fields:
          - { label: "Type", name: "type", widget: "select", options: ["gallery", "cta", "testimonial"], required: true }
          - { label: "Content", name: "content", widget: "text", required: false }
          - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }