backend:
  name: gitlab
  repo: AWD-2069/WPCJC
  branch: main
  auth_type: pkce
  app_id: 10bfa9d8d0fe5cbaca2b79693542aee0498a162912784c79d442b110ca7365d2

  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  # Sections Collection
  - name: "sections"
    label: "Sections"
    folder: "content/sections"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number", default: 0}

  # Pages Collection
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Section"
        name: "section"
        widget: "relation"
        collection: "sections"
        search_fields: ["title"]
        value_field: "{{slug}}"
        display_fields: ["title"]
        required: false
      - {label: "Body", name: "body", widget: "markdown"}