backend:
  name: gitlab
  repo: AWD-2069/WPCJC
  branch: main
  auth_type: pkce
  app_id: 10bfa9d8d0fe5cbaca2b79693542aee0498a162912784c79d442b110ca7365d2

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{path}}/{{name}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - label: "Hero Section"
        name: "hero"
        widget: "object"
        fields:
          - { label: "Heading", name: "heading", widget: "string", required: false }
          - { label: "Description", name: "hero_description", widget: "text", required: false }
          - { label: "Join Us Text", name: "join_us", widget: "string", required: false }
          - { label: "Background Image", name: "backgroundImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "leadership_staff"
    label: "Leadership & Staff"
    folder: "content/about-us"
    create: false
    slug: "leadership-staff"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - label: "Staff"
        name: "staff"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Description", name: "description", widget: "string" }
      - label: "Elders"
        name: "elders"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Description", name: "description", widget: "string" }
      - label: "Deacons"
        name: "deacons"
        widget: "list"
        required: false
        types:
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "Contact" }
              - { label: "Email", name: "email", widget: "string", required: true }
              - { label: "Phone", name: "phone", widget: "string", required: false }
          - label: "Card"
            name: "card"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "Card" }
              - { label: "Title", name: "title", widget: "string", required: true }
              - { label: "Image", name: "image", widget: "image", required: true }
          - label: "Text"
            name: "text"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "Text" }
              - { label: "Content", name: "content", widget: "markdown", required: true }
          - label: "Leadership Card"
            name: "leadershipCard"
            widget: "object"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "LeadershipCard" }
              - { label: "Name", name: "name", widget: "string", required: true }
              - { label: "Role", name: "role", widget: "string", required: true }
              - { label: "Image", name: "image", widget: "image", required: false }